# Generated by Django 6.0.3 on 2026-04-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_detached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="series_date",
            field=models.DateField(
                blank=True,
                help_text="The occurrence date for this instance within its series.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveSmallIntegerField(default=1)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday. Used for weekly recurrence.",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-31. Used for monthly/yearly recurrence.",
                        null=True,
                    ),
                ),
                (
                    "month_of_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-12. Used for yearly recurrence.",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("max_occurrences", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "deadline_offset",
                    models.IntegerField(
                        blank=True,
                        help_text="Days after occurrence date to set as deadline.",
                        null=True,
                    ),
                ),
                (
                    "generation_horizon",
                    models.DateField(
                        help_text="Instances have been generated up to this date."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="tasks.tasklist",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "recurrence series",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="tasks.recurrenceseries",
            ),
        ),
    ]
